[package]
name = "ts-pinger"
version = "1.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
eyre = "0.6.12"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
